"""One-shot: download both radar images, interpret, print + write status.json
plus inline data.js (browser-friendly) plus a copy for the main weather-forecast
project (so the 'Trenutno stanje' card can show radar status)."""

import json
import shutil
import sys
from pathlib import Path

import config
from radar import fetch, interpret, calibration, verification

BASE_DIR = Path(__file__).resolve().parent
DOCS_DIR = BASE_DIR / "docs"
OUTPUT_JSON = BASE_DIR / "output" / "status.json"
# Inline JS for the browser - works on file:// without CORS issues / local server
OUTPUT_JS = DOCS_DIR / "data.js"
# Public radar status (served via GH Pages and consumed by weather-forecast)
DOCS_STATUS_JSON = DOCS_DIR / "radar_status.json"
# Optional local sibling copy (only if weather-forecast lives next to budva-radar)
LOCAL_WEATHER_FORECAST_DOCS = Path("c:/Users/Matija/weather-forecast/docs/radar_status.json")
# Latest preview frames (for the HTML preview section in docs/index.html)
LATEST_DHMZ = DOCS_DIR / "latest_dhmz.png"
LATEST_OPERA = DOCS_DIR / "latest_opera.gif"


def _copy_latest_frames():
    """Copy the most recent frames into docs/ with stable names so the
    HTML preview can reference them via fixed paths."""
    DOCS_DIR.mkdir(exist_ok=True)
    for source_id, dest in [("dhmz", LATEST_DHMZ), ("opera", LATEST_OPERA)]:
        frames = fetch.list_cached_frames(source_id)
        if frames:
            try:
                shutil.copy2(frames[-1], dest)
            except Exception as e:
                print(f"  WARN: couldn't copy latest {source_id} frame: {e}")


def _add_budva_pixel(status_dict):
    """Embed Budva pixel coordinates + local pixel-per-km scale per source,
    so the HTML overlay can place the marker and draw concentric sampling
    rings at the correct radii."""
    import numpy as np
    for source_id, info in status_dict.get("sources", {}).items():
        if not info.get("ok"):
            continue
        try:
            cal = calibration.get_calibration(source_id)
            lat_c, lon_c = config.LOCATION["lat"], config.LOCATION["lon"]
            px, py = cal.latlon_to_pixel(lat_c, lon_c)
            # Compute local px-per-km using a 1-degree-latitude probe (works
            # for any projection; uses the actual local scale around Budva).
            px_n, py_n = cal.latlon_to_pixel(lat_c + 1.0, lon_c)
            pixels_per_deg_lat = float(np.hypot(px_n - px, py_n - py))
            km_per_deg_lat = 111.32
            px_per_km = pixels_per_deg_lat / km_per_deg_lat
            info["budva_pixel"] = {"x": round(px, 1), "y": round(py, 1)}
            info["image_size"] = list(config.SOURCES[source_id]["expected_size"])
            info["px_per_km"] = round(px_per_km, 4)
            # Ship the valid drawing zone so the browser cell-layer (shared
            # skala-cells-viz.js) can clip to the radar's coverage disc.
            va = config.SOURCES[source_id].get("valid_area")
            info["valid_area"] = list(va) if va else None
            rs = config.SOURCES[source_id].get("radar_site")
            info["radar_site"] = ({"lat": rs[0], "lon": rs[1], "range_km": rs[2]}
                                  if rs else None)
        except Exception:
            pass


def main():
    print("=" * 60)
    print("  budva-radar — fetch + interpret")
    print("=" * 60)

    print("\n[1/2] Fetch...")
    fetch_results = fetch.fetch_all()
    for r in fetch_results:
        status = "NEW" if r.get("fetched") else r.get("reason", "?")
        path = r.get("path", "")
        print(f"  {r['source']}: {status}  {path}")
        if r.get("error"):
            print(f"    ERROR: {r['error']}")

    print("\n[2/2] Interpret...")
    status = interpret.interpret_all()
    _add_budva_pixel(status)
    _copy_latest_frames()

    # 1) status.json (machine-readable)
    OUTPUT_JSON.parent.mkdir(exist_ok=True)
    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump(status, f, indent=2, ensure_ascii=False, default=str)
    print(f"\n  Saved: {OUTPUT_JSON}")

    # 2) data.js (inline for HTML — works on file:// without CORS)
    DOCS_DIR.mkdir(exist_ok=True)
    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by run.py; do not edit by hand.\n")
        f.write("window.RADAR_DATA = ")
        json.dump(status, f, indent=2, ensure_ascii=False, default=str)
        f.write(";\n")
    print(f"  Saved: {OUTPUT_JS}")

    # 3) docs/radar_status.json — public URL on GH Pages, fetched by the
    # main weather-forecast forecast.html (cross-origin via GH Pages CORS).
    with open(DOCS_STATUS_JSON, "w", encoding="utf-8") as f:
        json.dump(status, f, indent=2, ensure_ascii=False, default=str)
    print(f"  Saved: {DOCS_STATUS_JSON}")

    # 4) Optional sibling copy when running locally next to weather-forecast.
    if LOCAL_WEATHER_FORECAST_DOCS.parent.exists():
        with open(LOCAL_WEATHER_FORECAST_DOCS, "w", encoding="utf-8") as f:
            json.dump(status, f, indent=2, ensure_ascii=False, default=str)
        print(f"  Saved: {LOCAL_WEATHER_FORECAST_DOCS}")

    # 5) Mirror to Cloudflare R2 for instant serving (bypasses GH Pages build + CDN
    # cache); silent no-op if R2 isn't configured. See radar/r2_publish.py.
    from radar import r2_publish
    r2_publish.publish(["data.js", "radar_status.json", "latest_dhmz.png", "latest_opera.gif"])

    # Verification log: append one slim row per run, then re-score the
    # history. Best-effort; must never break the main output.
    row = verification.append_log(status, DOCS_DIR)
    if row is not None:
        print(f"  Log: appended scan to docs/skala_log_{str(row['generated'])[:4]}.csv")
    metrics = verification.score_log(DOCS_DIR)
    if metrics and metrics.get("n_scans_scored"):
        print(f"  Verify: POD={metrics.get('POD')} FAR={metrics.get('FAR')} "
              f"CSI={metrics.get('CSI')} (n={metrics.get('n_scans_scored')})")

    print()
    for line in status["summary"]["lines"]:
        print(f"  {line}")

    if status["summary"].get("rain_at_location"):
        print("\n  ALERT! Kisa pada na lokaciji")
    elif status["summary"]["rain_approaching"]:
        eta = status["summary"]["closest_eta_minutes"]
        print(f"\n  ALERT! Rain approaching — ETA ~{eta} min")
    else:
        print("\n  Status: ok, no precipitation heading toward Budva")

    return 0


if __name__ == "__main__":
    sys.exit(main())
